[build]
  command = "npm install"
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ytdl-core"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 