[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install && pip install yt-dlp"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9" 