[build]
  publish = "."
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ytdl-core", "openai"]

[[redirects]]
  from = "/.netlify/functions/transcribe"
  to = "/.netlify/functions/transcribe/index"
  status = 200

[[redirects]]
  from = "/.netlify/functions/transcribe/*"
  to = "/.netlify/functions/transcribe/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions."transcribe/*"]
  included_files = ["functions/transcribe/package.json"] 